# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageLEDState.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageLEDState.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15MessageLEDState.proto\"d\n\x0bLEDStateMsg\x12\x1e\n\neSystemLED\x18\x01 \x01(\x0e\x32\n.SystemLED\x12\x10\n\x08\x62\x45nabled\x18\x02 \x01(\x08\x12\x12\n\niIntensity\x18\x03 \x01(\r\x12\x0f\n\x07\x62\x46orced\x18\x04 \x01(\x08\",\n\tLEDSetMsg\x12\x1f\n\tmLEDState\x18\x01 \x01(\x0b\x32\x0c.LEDStateMsg\"0\n\x0eLEDGetStateMsg\x12\x1e\n\neSystemLED\x18\x01 \x01(\x0e\x32\n.SystemLED*\x97\x01\n\tSystemLED\x12\x0f\n\x0bLED_unknown\x10\x00\x12\x16\n\x12LED_Haematocrit_IR\x10\x01\x12\x19\n\x15LED_Haematocrit_Green\x10\x02\x12\x16\n\x12LED_Chemistry_Blue\x10\x03\x12\x15\n\x11LED_Chemistry_Red\x10\x04\x12\x17\n\x13LED_SampleDetection\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageLEDState_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMLED']._serialized_start=224
  _globals['_SYSTEMLED']._serialized_end=375
  _globals['_LEDSTATEMSG']._serialized_start=25
  _globals['_LEDSTATEMSG']._serialized_end=125
  _globals['_LEDSETMSG']._serialized_start=127
  _globals['_LEDSETMSG']._serialized_end=171
  _globals['_LEDGETSTATEMSG']._serialized_start=173
  _globals['_LEDGETSTATEMSG']._serialized_end=221
# @@protoc_insertion_point(module_scope)
