# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageResponse.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15MessageResponse.proto\"/\n\x0bResponseMsg\x12 \n\teResponse\x18\x01 \x01(\x0e\x32\r.ResponseEnum*[\n\x0cResponseEnum\x12\x11\n\reResp_Unknown\x10\x00\x12\x0f\n\x0b\x65Resp_MsgOK\x10\x05\x12\x11\n\reResp_MsgFAIL\x10\n\x12\x14\n\x0e\x65Resp_Reserved\x10\xff\xff\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEENUM']._serialized_start=74
  _globals['_RESPONSEENUM']._serialized_end=165
  _globals['_RESPONSEMSG']._serialized_start=25
  _globals['_RESPONSEMSG']._serialized_end=72
# @@protoc_insertion_point(module_scope)
