# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageVersion.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageVersion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14MessageVersion.proto\x1a\x0cnanopb.proto\".\n\x0c\x46WVersionMsg\x12\x0e\n\x06iMajor\x18\x01 \x01(\x05\x12\x0e\n\x06iMinor\x18\x02 \x01(\x05\" \n\rGetVersionMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\"P\n\nVersionMsg\x12!\n\nmFWVersion\x18\x01 \x01(\x0b\x32\r.FWVersionMsg\x12\x1f\n\x0fsVersionDetails\x18\x02 \x01(\tB\x06\x92?\x03p\x96\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageVersion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONMSG'].fields_by_name['sVersionDetails']._loaded_options = None
  _globals['_VERSIONMSG'].fields_by_name['sVersionDetails']._serialized_options = b'\222?\003p\226\001'
  _globals['_FWVERSIONMSG']._serialized_start=38
  _globals['_FWVERSIONMSG']._serialized_end=84
  _globals['_GETVERSIONMSG']._serialized_start=86
  _globals['_GETVERSIONMSG']._serialized_end=118
  _globals['_VERSIONMSG']._serialized_start=120
  _globals['_VERSIONMSG']._serialized_end=200
# @@protoc_insertion_point(module_scope)
