# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageBatteryCharger.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageBatteryCharger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bMessageBatteryCharger.proto\"o\n\x14\x42\x61tteryChargerSetMsg\x12\x1d\n\x15iMinimumSystemVoltage\x18\x01 \x01(\r\x12\x1b\n\x13iChargeVoltageLimit\x18\x02 \x01(\r\x12\x1b\n\x13iChargeCurrentLimit\x18\x03 \x01(\r\"\xdc\x01\n\x16\x42\x61tteryChargerStateMsg\x12\x17\n\x0f\x66\x42\x61tteryVoltage\x18\x01 \x01(\x02\x12\x17\n\x0f\x66\x42\x61tteryCurrent\x18\x02 \x01(\x02\x12\x17\n\x0f\x66\x43hargerVoltage\x18\x03 \x01(\x02\x12\x17\n\x0f\x66\x43hargerCurrent\x18\x04 \x01(\x02\x12\x13\n\x0biFaultFlag1\x18\x05 \x01(\r\x12\x13\n\x0biFaultFlag2\x18\x06 \x01(\r\x12\x19\n\x11\x62\x43hargerConnected\x18\x07 \x01(\x08\x12\x19\n\x11\x62\x42\x61tteryConnected\x18\x08 \x01(\x08\",\n\x19\x42\x61tteryChargerGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageBatteryCharger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATTERYCHARGERSETMSG']._serialized_start=31
  _globals['_BATTERYCHARGERSETMSG']._serialized_end=142
  _globals['_BATTERYCHARGERSTATEMSG']._serialized_start=145
  _globals['_BATTERYCHARGERSTATEMSG']._serialized_end=365
  _globals['_BATTERYCHARGERGETSTATEMSG']._serialized_start=367
  _globals['_BATTERYCHARGERGETSTATEMSG']._serialized_end=411
# @@protoc_insertion_point(module_scope)
