# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageCurrentSensor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageCurrentSensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aMessageCurrentSensor.proto\"{\n\x15\x43urrentSensorStateMsg\x12&\n\x0e\x65\x43urrentSensor\x18\x01 \x01(\x0e\x32\x0e.CurrentSensor\x12\x13\n\x0b\x66\x43urrent_mA\x18\x02 \x01(\x02\x12\x12\n\nfVoltage_V\x18\x03 \x01(\x02\x12\x11\n\tfPower_mW\x18\x04 \x01(\x02\"}\n\x18\x43urrentSensorStateAllMsg\x12\x30\n\x10mMicroscopeBoard\x18\x01 \x01(\x0b\x32\x16.CurrentSensorStateMsg\x12/\n\x0fmAuxiliaryBoard\x18\x02 \x01(\x0b\x32\x16.CurrentSensorStateMsg\"S\n\x18\x43urrentSensorGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\x12&\n\x0e\x65\x43urrentSensor\x18\x02 \x01(\x0e\x32\x0e.CurrentSensor\".\n\x1b\x43urrentSensorGetAllStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08*T\n\rCurrentSensor\x12!\n\x1d\x43urrentSensor_MicroscopeBoard\x10\x00\x12 \n\x1c\x43urrentSensor_AuxiliaryBoard\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageCurrentSensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENTSENSOR']._serialized_start=415
  _globals['_CURRENTSENSOR']._serialized_end=499
  _globals['_CURRENTSENSORSTATEMSG']._serialized_start=30
  _globals['_CURRENTSENSORSTATEMSG']._serialized_end=153
  _globals['_CURRENTSENSORSTATEALLMSG']._serialized_start=155
  _globals['_CURRENTSENSORSTATEALLMSG']._serialized_end=280
  _globals['_CURRENTSENSORGETSTATEMSG']._serialized_start=282
  _globals['_CURRENTSENSORGETSTATEMSG']._serialized_end=365
  _globals['_CURRENTSENSORGETALLSTATEMSG']._serialized_start=367
  _globals['_CURRENTSENSORGETALLSTATEMSG']._serialized_end=413
# @@protoc_insertion_point(module_scope)
