# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageMotionDetection.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageMotionDetection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cMessageMotionDetection.proto\"\xe0\x01\n\x17MotionDetectionStateMsg\x12\x17\n\x0f\x62MotionDetected\x18\x01 \x01(\x08\x12\x15\n\rbTiltDetected\x18\x02 \x01(\x08\x12\x1a\n\x12\x62VibrationDetected\x18\x03 \x01(\x08\x12\x1a\n\x12iMaxMotionDetected\x18\x04 \x01(\r\x12\x18\n\x10\x66MaxTiltDetected\x18\x05 \x01(\x02\x12!\n\x19\x66MaxFreqVibrationDetected\x18\x06 \x01(\x02\x12 \n\x18\x66MaxAmpVibrationDetected\x18\x07 \x01(\r\"y\n\x1cMotionDetectionClearStateMsg\x12\x1c\n\x14\x62\x43learMotionDetected\x18\x01 \x01(\x08\x12\x1a\n\x12\x62\x43learTiltDetected\x18\x02 \x01(\x08\x12\x1f\n\x17\x62\x43learVibrationDetected\x18\x03 \x01(\x08\"-\n\x1aMotionDetectionGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\"\x94\x01\n\x1fMotionDetectionSettingsStateMsg\x12\x18\n\x10iMotionThreshold\x18\x01 \x01(\r\x12\x16\n\x0e\x66TiltThreshold\x18\x02 \x01(\x02\x12\x1f\n\x17\x66\x46reqVibrationThreshold\x18\x03 \x01(\x02\x12\x1e\n\x16\x66\x41mpVibrationThreshold\x18\x04 \x01(\r\"\x92\x01\n\x1dMotionDetectionSetSettingsMsg\x12\x18\n\x10iMotionThreshold\x18\x01 \x01(\r\x12\x16\n\x0e\x66TiltThreshold\x18\x02 \x01(\x02\x12\x1f\n\x17\x66\x46reqVibrationThreshold\x18\x03 \x01(\x02\x12\x1e\n\x16\x66\x41mpVibrationThreshold\x18\x04 \x01(\r\"0\n\x1dMotionDetectionGetSettingsMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageMotionDetection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONDETECTIONSTATEMSG']._serialized_start=33
  _globals['_MOTIONDETECTIONSTATEMSG']._serialized_end=257
  _globals['_MOTIONDETECTIONCLEARSTATEMSG']._serialized_start=259
  _globals['_MOTIONDETECTIONCLEARSTATEMSG']._serialized_end=380
  _globals['_MOTIONDETECTIONGETSTATEMSG']._serialized_start=382
  _globals['_MOTIONDETECTIONGETSTATEMSG']._serialized_end=427
  _globals['_MOTIONDETECTIONSETTINGSSTATEMSG']._serialized_start=430
  _globals['_MOTIONDETECTIONSETTINGSSTATEMSG']._serialized_end=578
  _globals['_MOTIONDETECTIONSETSETTINGSMSG']._serialized_start=581
  _globals['_MOTIONDETECTIONSETSETTINGSMSG']._serialized_end=727
  _globals['_MOTIONDETECTIONGETSETTINGSMSG']._serialized_start=729
  _globals['_MOTIONDETECTIONGETSETTINGSMSG']._serialized_end=777
# @@protoc_insertion_point(module_scope)
