# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageBrokerControl.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageBrokerControl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageResponse_pb2 as MessageResponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aMessageBrokerControl.proto\x1a\x15MessageResponse.proto\"$\n\x0cSubscribeMsg\x12\x14\n\x0ciMessageKind\x18\x01 \x01(\r\"&\n\x0eUnsubscribeMsg\x12\x14\n\x0ciMessageKind\x18\x01 \x01(\r\"3\n\x0fSubscribeAckMsg\x12 \n\teResponse\x18\x01 \x01(\x0e\x32\r.ResponseEnumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageBrokerControl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEMSG']._serialized_start=53
  _globals['_SUBSCRIBEMSG']._serialized_end=89
  _globals['_UNSUBSCRIBEMSG']._serialized_start=91
  _globals['_UNSUBSCRIBEMSG']._serialized_end=129
  _globals['_SUBSCRIBEACKMSG']._serialized_start=131
  _globals['_SUBSCRIBEACKMSG']._serialized_end=182
# @@protoc_insertion_point(module_scope)
