# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageIncubator.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageIncubator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MessageIncubator.proto\"r\n\x0fIncubatorSetMsg\x12\x10\n\x08\x62\x45nabled\x18\x01 \x01(\x08\x12\x1a\n\x12\x66TargetTemperature\x18\x02 \x01(\x02\x12\x0f\n\x07\x66PID_KP\x18\x03 \x01(\x02\x12\x0f\n\x07\x66PID_KI\x18\x04 \x01(\x02\x12\x0f\n\x07\x66PID_KD\x18\x05 \x01(\x02\"\xae\x01\n\x11IncubatorStateMsg\x12\x10\n\x08\x62\x45nabled\x18\x01 \x01(\x08\x12\x1a\n\x12\x66TargetTemperature\x18\x02 \x01(\x02\x12\x0f\n\x07\x66PID_KP\x18\x03 \x01(\x02\x12\x0f\n\x07\x66PID_KI\x18\x04 \x01(\x02\x12\x0f\n\x07\x66PID_KD\x18\x05 \x01(\x02\x12\x10\n\x08\x66PID_Out\x18\x06 \x01(\x02\x12\x12\n\nfTempSens1\x18\x07 \x01(\x02\x12\x12\n\nfTempSens2\x18\x08 \x01(\x02\"\'\n\x14GetIncubatorStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\"m\n\x17IncubatorAdvancedSetMsg\x12(\n\x0emInnerPIDState\x18\x01 \x01(\x0b\x32\x10.IncubatorSetMsg\x12(\n\x0emOuterPIDState\x18\x02 \x01(\x0b\x32\x10.IncubatorSetMsg\"s\n\x19IncubatorAdvancedStateMsg\x12*\n\x0emInnerPIDState\x18\x01 \x01(\x0b\x32\x12.IncubatorStateMsg\x12*\n\x0emOuterPIDState\x18\x02 \x01(\x0b\x32\x12.IncubatorStateMsg\"/\n\x1cGetIncubatorAdvancedStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageIncubator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INCUBATORSETMSG']._serialized_start=26
  _globals['_INCUBATORSETMSG']._serialized_end=140
  _globals['_INCUBATORSTATEMSG']._serialized_start=143
  _globals['_INCUBATORSTATEMSG']._serialized_end=317
  _globals['_GETINCUBATORSTATEMSG']._serialized_start=319
  _globals['_GETINCUBATORSTATEMSG']._serialized_end=358
  _globals['_INCUBATORADVANCEDSETMSG']._serialized_start=360
  _globals['_INCUBATORADVANCEDSETMSG']._serialized_end=469
  _globals['_INCUBATORADVANCEDSTATEMSG']._serialized_start=471
  _globals['_INCUBATORADVANCEDSTATEMSG']._serialized_end=586
  _globals['_GETINCUBATORADVANCEDSTATEMSG']._serialized_start=588
  _globals['_GETINCUBATORADVANCEDSTATEMSG']._serialized_end=635
# @@protoc_insertion_point(module_scope)
