# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageFan.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageFan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10MessageFan.proto\"=\n\x0b\x46\x61nStateMsg\x12\x12\n\nfStartTemp\x18\x01 \x01(\x02\x12\x1a\n\x06\x65State\x18\x02 \x01(\x0e\x32\n.eFanState\"I\n\tFanSetMsg\x12\x14\n\nfStartTemp\x18\x01 \x01(\x02H\x00\x12\x1c\n\x06\x65State\x18\x02 \x01(\x0e\x32\n.eFanStateH\x00\x42\x08\n\x06\x46\x61nSet\"!\n\x0e\x46\x61nGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08*Q\n\teFanState\x12\x15\n\x11\x65\x46\x61nState_Inhibit\x10\x00\x12\x19\n\x15\x65\x46\x61nState_ForcedStart\x10\x01\x12\x12\n\x0e\x65\x46\x61nState_Auto\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageFan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EFANSTATE']._serialized_start=193
  _globals['_EFANSTATE']._serialized_end=274
  _globals['_FANSTATEMSG']._serialized_start=20
  _globals['_FANSTATEMSG']._serialized_end=81
  _globals['_FANSETMSG']._serialized_start=83
  _globals['_FANSETMSG']._serialized_end=156
  _globals['_FANGETSTATEMSG']._serialized_start=158
  _globals['_FANGETSTATEMSG']._serialized_end=191
# @@protoc_insertion_point(module_scope)
