# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageBeacon.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageBeacon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MessageBeacon.proto\x1a\x0cnanopb.proto\"f\n\x0c\x42\x65\x61\x63onScheme\x12\"\n\x0c\x65ProfileMode\x18\x01 \x01(\x0e\x32\x0c.ProfileMode\x12 \n\x08mProfile\x18\x02 \x01(\x0b\x32\x0e.BeaconProfile\x12\x10\n\x08iCounter\x18\x03 \x01(\r\"P\n\rBeaconProfile\x12%\n\tmArrSteps\x18\x01 \x03(\x0b\x32\x0b.BeaconStepB\x05\x92?\x02\x10(\x12\x18\n\x10iStepDuration_ms\x18\x03 \x01(\r\"%\n\nBeaconStep\x12\x17\n\x08mArrLEDs\x18\x01 \x03(\rB\x05\x92?\x02\x10\n\"[\n\x0c\x42\x65\x61\x63onSetMsg\x12\x1a\n\x05\x65Mode\x18\x01 \x01(\x0e\x32\x0b.BeaconMode\x12#\n\x07mScheme\x18\x02 \x01(\x0b\x32\r.BeaconSchemeH\x00\x88\x01\x01\x42\n\n\x08_mScheme\"]\n\x0e\x42\x65\x61\x63onStateMsg\x12\x1a\n\x05\x65Mode\x18\x01 \x01(\x0e\x32\x0b.BeaconMode\x12#\n\x07mScheme\x18\x02 \x01(\x0b\x32\r.BeaconSchemeH\x00\x88\x01\x01\x42\n\n\x08_mScheme\"$\n\x11\x42\x65\x61\x63onGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08*\xca\x01\n\nBeaconMode\x12\x0e\n\nBM_Unknown\x10\x00\x12\x0b\n\x07\x42M_Stop\x10\x01\x12\n\n\x06\x42M_Off\x10\x02\x12\x13\n\x0f\x42M_Initialising\x10\x03\x12\x12\n\x0e\x42M_ReadyForUse\x10\x04\x12\x17\n\x13\x42M_LowPriorityAlarm\x10\x05\x12\x1a\n\x16\x42M_MediumPriorityAlarm\x10\x06\x12\x18\n\x14\x42M_HighPriorityAlarm\x10\x07\x12\x0c\n\x08\x42M_Fault\x10\x08\x12\r\n\tBM_Custom\x10\t*@\n\x0bProfileMode\x12\x0e\n\nPM_Unknown\x10\x00\x12\x11\n\rPM_Continuous\x10\x01\x12\x0e\n\nPM_Counter\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageBeacon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BEACONPROFILE'].fields_by_name['mArrSteps']._loaded_options = None
  _globals['_BEACONPROFILE'].fields_by_name['mArrSteps']._serialized_options = b'\222?\002\020('
  _globals['_BEACONSTEP'].fields_by_name['mArrLEDs']._loaded_options = None
  _globals['_BEACONSTEP'].fields_by_name['mArrLEDs']._serialized_options = b'\222?\002\020\n'
  _globals['_BEACONMODE']._serialized_start=489
  _globals['_BEACONMODE']._serialized_end=691
  _globals['_PROFILEMODE']._serialized_start=693
  _globals['_PROFILEMODE']._serialized_end=757
  _globals['_BEACONSCHEME']._serialized_start=37
  _globals['_BEACONSCHEME']._serialized_end=139
  _globals['_BEACONPROFILE']._serialized_start=141
  _globals['_BEACONPROFILE']._serialized_end=221
  _globals['_BEACONSTEP']._serialized_start=223
  _globals['_BEACONSTEP']._serialized_end=260
  _globals['_BEACONSETMSG']._serialized_start=262
  _globals['_BEACONSETMSG']._serialized_end=353
  _globals['_BEACONSTATEMSG']._serialized_start=355
  _globals['_BEACONSTATEMSG']._serialized_end=448
  _globals['_BEACONGETSTATEMSG']._serialized_start=450
  _globals['_BEACONGETSTATEMSG']._serialized_end=486
# @@protoc_insertion_point(module_scope)
