# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageDoor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageDoor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MessageDoor.proto\"\x1f\n\x0c\x44oorStateMsg\x12\x0f\n\x07\x62\x43losed\x18\x01 \x01(\x08\"\"\n\x0f\x44oorGetStateMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageDoor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOORSTATEMSG']._serialized_start=21
  _globals['_DOORSTATEMSG']._serialized_end=52
  _globals['_DOORGETSTATEMSG']._serialized_start=54
  _globals['_DOORGETSTATEMSG']._serialized_end=88
# @@protoc_insertion_point(module_scope)
