# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessagePhotodiode.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessagePhotodiode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17MessagePhotodiode.proto\"y\n\x0fPhotodiodeState\x12\x10\n\x08\x62\x45nabled\x18\x01 \x01(\x08\x12\x1e\n\x05\x65Gain\x18\x02 \x01(\x0e\x32\x0f.PhotodiodeGain\x12\x34\n\x10\x65IntegrationTime\x18\x03 \x01(\x0e\x32\x1a.PhotodiodeIntegrationTime\"A\n\x11PhotodiodeReading\x12\r\n\x05iFull\x18\x01 \x01(\r\x12\x0b\n\x03iIR\x18\x02 \x01(\r\x12\x10\n\x08iVisible\x18\x03 \x01(\r\"l\n\x10PhotodiodeSetMsg\x12,\n\x11\x65SystemPhotodiode\x18\x01 \x01(\x0e\x32\x11.SystemPhotodiode\x12*\n\x10mPhotodiodeState\x18\x02 \x01(\x0b\x32\x10.PhotodiodeState\"p\n\x12PhotodiodeStateMsg\x12*\n\x10mPhotodiodeState\x18\x01 \x01(\x0b\x32\x10.PhotodiodeState\x12.\n\x12mPhotodiodeReading\x18\x02 \x01(\x0b\x32\x12.PhotodiodeReading\"@\n\x10PhotodiodeGetMsg\x12,\n\x11\x65SystemPhotodiode\x18\x01 \x01(\x0e\x32\x11.SystemPhotodiode*}\n\x10SystemPhotodiode\x12\x0e\n\nPD_unknown\x10\x00\x12\x12\n\x0ePD_Haematocrit\x10\x01\x12\x16\n\x12PD_SampleDetection\x10\x02\x12\x16\n\x12PD_DiagnosticsBlue\x10\x03\x12\x15\n\x11PD_DiagnosticsRed\x10\x04*X\n\x0ePhotodiodeGain\x12\x0f\n\x0bPD_GAIN_LOW\x10\x00\x12\x12\n\x0ePD_GAIN_MEDIUM\x10\x10\x12\x10\n\x0cPD_GAIN_HIGH\x10 \x12\x0f\n\x0bPD_GAIN_MAX\x10\x30*\xc9\x01\n\x19PhotodiodeIntegrationTime\x12\x1b\n\x17PD_INTEGRATION_TIME_100\x10\x00\x12\x1b\n\x17PD_INTEGRATION_TIME_200\x10\x01\x12\x1b\n\x17PD_INTEGRATION_TIME_300\x10\x02\x12\x1b\n\x17PD_INTEGRATION_TIME_400\x10\x03\x12\x1b\n\x17PD_INTEGRATION_TIME_500\x10\x04\x12\x1b\n\x17PD_INTEGRATION_TIME_600\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessagePhotodiode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMPHOTODIODE']._serialized_start=507
  _globals['_SYSTEMPHOTODIODE']._serialized_end=632
  _globals['_PHOTODIODEGAIN']._serialized_start=634
  _globals['_PHOTODIODEGAIN']._serialized_end=722
  _globals['_PHOTODIODEINTEGRATIONTIME']._serialized_start=725
  _globals['_PHOTODIODEINTEGRATIONTIME']._serialized_end=926
  _globals['_PHOTODIODESTATE']._serialized_start=27
  _globals['_PHOTODIODESTATE']._serialized_end=148
  _globals['_PHOTODIODEREADING']._serialized_start=150
  _globals['_PHOTODIODEREADING']._serialized_end=215
  _globals['_PHOTODIODESETMSG']._serialized_start=217
  _globals['_PHOTODIODESETMSG']._serialized_end=325
  _globals['_PHOTODIODESTATEMSG']._serialized_start=327
  _globals['_PHOTODIODESTATEMSG']._serialized_end=439
  _globals['_PHOTODIODEGETMSG']._serialized_start=441
  _globals['_PHOTODIODEGETMSG']._serialized_end=505
# @@protoc_insertion_point(module_scope)
