# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MessageAccelerometer.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'MessageAccelerometer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aMessageAccelerometer.proto\x1a\x0cnanopb.proto\"/\n\x1c\x41\x63\x63\x65lerometerGetNumBufferMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\"2\n\x1a\x41\x63\x63\x65lerometerNumBuffersMsg\x12\x14\n\x0ciBufferCount\x18\x01 \x01(\r\"*\n\x17\x41\x63\x63\x65lerometerGetDataMsg\x12\x0f\n\x07\x62\x41\x63tive\x18\x01 \x01(\x08\"+\n\x14\x41\x63\x63\x65lerometerDataMsg\x12\x13\n\x0bmArrSamples\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MessageAccelerometer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCELEROMETERGETNUMBUFFERMSG']._serialized_start=44
  _globals['_ACCELEROMETERGETNUMBUFFERMSG']._serialized_end=91
  _globals['_ACCELEROMETERNUMBUFFERSMSG']._serialized_start=93
  _globals['_ACCELEROMETERNUMBUFFERSMSG']._serialized_end=143
  _globals['_ACCELEROMETERGETDATAMSG']._serialized_start=145
  _globals['_ACCELEROMETERGETDATAMSG']._serialized_end=187
  _globals['_ACCELEROMETERDATAMSG']._serialized_start=189
  _globals['_ACCELEROMETERDATAMSG']._serialized_end=232
# @@protoc_insertion_point(module_scope)
